const DEFAULT_SEPARATOR_SIZE = 10;
const DEFAULT_BORDER_RADIUS = 15;
const DEFAULT_IS_RTL = false;
const DEFAULT_DECELERATION_RATE = 'fast';
const DEFAULT_STICKY_ITEM_ACTIVE_OPACITY = 0.25;

export {
  DEFAULT_SEPARATOR_SIZE,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_IS_RTL,
  DEFAULT_DECELERATION_RATE,
  DEFAULT_STICKY_ITEM_ACTIVE_OPACITY,
};
